language: go
go:
  - 1.6
  - tip
before_script:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script: go test -v -covermode=count -coverprofile=coverage.out go test $(go list ./... | grep -v '/vendor/')
after_success:
    - $HOME/gopath/bin/goveralls -covermode=count -coverprofile=coverage.out -service=travis-ci