language: go
go:
  - 1.6
  - tip
before_script:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script: 
   - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
    
after_success:
    - $HOME/gopath/bin/goveralls -covermode=count -coverprofile=substitute.coverprofile -service=travis-ci